### ISSUE TITLE
Ignite cant load the api of paper plugin

### ISSUE THREAD

**Issue by FrankHan052176** [Mineteria-Development/Ignite#174]
My Server version:
This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Mixin version: 0.8.5

In my injected function, i use the api of MythicMobs, but it throw the error
```
[20:34:13 WARN]: Unexpected exception while parsing console command "summon mythicmobs:test -1351 104 4384"
org.bukkit.command.CommandException: Unhandled exception executing 'summon mythicmobs:test -1351 104 4384' in org.bukkit.craftbukkit.v1_20_R1.command.VanillaCommandWrapper(summon)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987) ~[?:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:972) ~[?:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[?:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[?:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[?:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[?:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[?:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: io/lumine/mythic/bukkit/MythicBukkit
        at top.missingbyriver.ignitemodify.mixin.plugins.FakeEntity.b(FakeEntity.java:44) ~[?:?]
        at net.minecraft.server.commands.SummonCommand.lambda$createEntity$4(SummonCommand.java:59) ~[?:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraft.world.entity.EntityType.loadEntityRecursive(EntityType.java:615) ~[?:?]
        at net.minecraft.server.commands.SummonCommand.createEntity(SummonCommand.java:58) ~[?:?]
        at net.minecraft.server.commands.SummonCommand.spawnEntity(SummonCommand.java:81) ~[?:?]
        at net.minecraft.server.commands.SummonCommand.lambda$register$2(SummonCommand.java:42) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:303) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[?:git-Paper-196]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[?:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: io.lumine.mythic.bukkit.MythicBukkit
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at space.vectrix.ignite.launch.ember.EmberClassLoader.loadClass(EmberClassLoader.java:163) ~[ignite.jar:1.0.1]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at top.missingbyriver.ignitemodify.mixin.plugins.FakeEntity.b(FakeEntity.java:44) ~[?:?]
        at net.minecraft.server.commands.SummonCommand.lambda$createEntity$4(SummonCommand.java:59) ~[?:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraft.world.entity.EntityType.loadEntityRecursive(EntityType.java:615) ~[?:?]
        at net.minecraft.server.commands.SummonCommand.createEntity(SummonCommand.java:58) ~[?:?]
        at net.minecraft.server.commands.SummonCommand.spawnEntity(SummonCommand.java:81) ~[?:?]
        at net.minecraft.server.commands.SummonCommand.lambda$register$2(SummonCommand.java:42) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:303) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[?:git-Paper-196]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[?:?]
        ... 8 more
```

**Comment by FrankHan052176** [comment]
i guess it's caused by minecraft classloader cant load the class which loaded by bukkit classloader?

**Comment by vectrixdevelops** [comment]
Yeah at the time mixin is injecting, the plugins have not been class loaded. There's no easy way to mixin to a plugin. If you need further help feel free to ask in the Discord.
