### ISSUE TITLE
Legacy Paper game locator doesn't load on Java 21

### ISSUE THREAD

**Issue by ManInMyVan** [Mineteria-Development/Ignite#190]
```
[19:44:21] [main/INFO]: Running ignite v1.1.0 (API: 1.1, ASM: ASM 9.7 (ASM10_EXPERIMENTAL), Java: 21.0)
[19:44:21] [main/INFO]: Detected game locator: Legacy Paper
[19:44:21] [main/ERROR]: Failed to start game: Unable to apply GameLocator service.: java.lang.RuntimeException: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at space.vectrix.ignite.game.LegacyPaperGameLocator.apply(LegacyPaperGameLocator.java:125)
        at space.vectrix.ignite.IgniteBootstrap.run(IgniteBootstrap.java:132)
        at space.vectrix.ignite.IgniteBootstrap.main(IgniteBootstrap.java:74)
Caused by: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:430)
        at space.vectrix.ignite.game.LegacyPaperGameLocator.apply(LegacyPaperGameLocator.java:99)
        ... 2 more
```

**Comment by vectrixdevelops** [comment]
What version of Paper are you attempting to start?

**Comment by ManInMyVan** [comment]
pandaspigot (1.8.8)

**Comment by vectrixdevelops** [comment]
The legacy paper game locator service currently does not support Java 18 or higher. I'll consider adding a fallback or updating the documentation to reflect the incompatibility.
